name: Main workflow

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add repository
        run: add-apt-repository ppa:avsm/ppa
            
      - name: Update
        run: apt update
        
      - name: Opam install
        run: apt install -y opam
        
      - name: Opam init
        run: |
          opam init
          eval $(opam env)
          opam switch create 4.12.0
          eval $(opam env)

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
